
<center> <h1> <u>NUMPY PRACTICE QUESTIONS </h1> </center> </u> <br/>
<b>
1.	Generate a tuple from the set ["aman", "222", 777, 400.4] <br/>
2.	Create a dictionary of your basic data : (a) Roll No (b) Last Name (c) First Name (d) Date of birth. Print out the values and keys. <br/>
3.	Use rand function to generate a 2-dimensional random array with seed.<br/>
4.	Generate a single random number in [0.0, 1.0].Find the absolute value of (-1234)<br/>
5.	Return a random integer N such that 20 <= N <= 90. <br/>
6.	Given a population or set[11, 12, 13,14, 15] <br/>
o	Return a 3 length list of unique elements without replacement.<br/>
o	Shuffle the above set<br/>
o	Print a random number from the set<br/>
7.	Write the text "The King is Dead, Long Live The King" on to a file in your hard drive; read and print the text.<br/>
8.	Create an illustrative function to demonstrate use of: if, elif and else (b) for, while, break and continue. <br/>
9.	Given a string "The King is Dead, Long Live The King" <br/>
o	Print the complete string<br/>
o	Print first character of the string<br/>
o	Print characters starting from 3rd to 5th<br/>
o	Print string starting from 3rd character<br/>
o	Split the words<br/>
10.	An array can be created from a list:  Create an array from a list comprising of numbers 1,4,5,8 (treat them as floats).Slice the above array to display first and second elements<br/>
11.	Arrays can be multidimensional. Create a two-dimensional array of (1,2,3) and (4,5,6).<br/>
12.	Array slicing works with multiple dimensions in the same way as usual, applying each slice specification as a filter to a specified dimension.Consider two-dimensional array of (1,2,3) and (4,5,6).<br/>
o	Slice and display the 2nd row.<br/>
o	Write code to display as array([2., 5.]) <br/>
o	Find the length of the array.<br/>
13.	Arrays can be reshaped using tuples that specify new dimensions. Turn a ten-element one-dimensional array into a two-dimensional one whose first axis has five elements and whose second axis has two elements. Obtain the transpose of the array<br/>
14.	Create an array from a list of 1,2 and 3.<br/>
15.	Fill an array [1,2,3] with a single value [9,9,9]. <br/>
16.	Sum the elements of array [2,4,5].<br/>
17.	Give the products of array [77,74,75]<br/>
18.	Given an array [2,1,9,1,2,22,1,1,4,55,6,2,56]. Find mean, variance, max, min, argmin, median, argmax and standard deviation.<br/>
19.	Extract unique elements from an array: [1, 1, 4, 5, 5, 5, 7] and sort it.<br/>
20.	Find dot product of two arrays [1, 2, 3]and [0, 1, 1].<br/>
21.	Find the eigenvalues and eigenvectors of matrix A.<br/>
22.	Given an array with [11, 22, 11, 31], [25, 33, 31, 28]]. Treat as floats. Find the correlation coefficients.<br/>
</b>

In [208]:
import pandas as pd
import numpy as np

In [59]:
a=["aman", "222", 777, 400.4]
print(tuple(a))

('aman', '222', 777, 400.4)


In [61]:
a={"Roll.No":"CN.EN.U4CSE21468","Last_Name":"Ramasubramanian","First_Name":"Viswaa","DOB":"07-11-2003"}
print(a)

{'Roll.No': 'CN.EN.U4CSE21468', 'Last_Name': 'Ramasubramanian', 'First_Name': 'Viswaa', 'DOB': '07-11-2003'}


In [72]:
a=np.random.randint(2,4,(5,2))
print(a)

[[2 3]
 [3 3]
 [3 3]
 [2 3]
 [3 3]]


In [91]:
a=np.random.ranf()
print(a)

0.9741037452664022


In [93]:
a=np.absolute(-1234)
a

1234

In [95]:
a=np.random.randint(20,91)
a

54

In [102]:
#Given a population or set[11, 12, 13,14, 15] 
#Return a 3 length list of unique elements without replacement.
a=np.array([11,12,13,14,15])
b=np.random.choice(a,size=3,replace=False)
list(b)

[13, 14, 11]

In [105]:
#Shuffle the above set
c=np.random.permutation(a)
c

array([12, 15, 11, 14, 13])

In [110]:
#Print a random number from the set
d=np.random.choice(a)
d

14

In [129]:
# Write the text "The King is Dead, Long Live The King" on to a file in your hard drive; read and print the text.
a=pd.read_csv("C:\\Users\\viswa\\Data Science and ML\\Datasets\\DS Datasets\\practice.txt")

In [130]:
type(a)

pandas.core.frame.DataFrame

In [131]:
a

Empty DataFrame
Columns: [The King is Dead,  Long Live The King]
Index: []

In [141]:
#Q9
a="The King is Dead, Long Live The King"
print(a)
print(a[0],end="\n")
print(a[2:5])
print(a[2:])
a=a.split(" ")
print(a)

The King is Dead, Long Live The King
T
e K
e King is Dead, Long Live The King
['The', 'King', 'is', 'Dead,', 'Long', 'Live', 'The', 'King']


In [145]:
a=[1,4,5,8]
b=np.array(a,dtype="float32")
b

array([1., 4., 5., 8.], dtype=float32)

In [156]:
a=np.array([[1,2,3],[4,5,6]])

print(a[1])

b=np.array([a[0][1],a[1][1]],dtype="float32")
print(b)

print(len(a))
print(a.shape)

[4 5 6]
[2. 5.]
2
(2, 3)


In [167]:
#Arrays can be reshaped using tuples that specify new dimensions. Turn a ten-element one-dimensional array into a two-dimensional one whose first axis has five elements and whose second axis has two elements. Obtain the transpose of the array
a=np.arange(1,11)
print(a)
print(a.shape)
print()
b=np.reshape(a,(5,2))
print(b)
print(b.shape)
print()
c=np.transpose(b)
print(c)
print(c.shape)

[ 1  2  3  4  5  6  7  8  9 10]
(10,)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
(5, 2)

[[ 1  3  5  7  9]
 [ 2  4  6  8 10]]
(2, 5)


In [172]:
#Fill an array [1,2,3] with a single value [9,9,9]. 
a=[1,2,3]
b=np.full_like(a,9)
b

array([9, 9, 9])

In [174]:
a=np.array([2,4,5])
print(np.sum(a))
print(np.prod(a))

11
40


In [185]:
a=np.array([2,1,9,1,2,22,1,1,4,55,6,2,56])
print(np.mean(a))
print(np.var(a))
print(np.max(a))
print(np.min(a))
print(np.argmin(a))
print(np.median(a))
print(np.argmax(a))
print(np.std(a))

12.461538461538462
367.32544378698225
56
1
1
2.0
12
19.165736192147232


In [190]:
#Extract unique elements from an array: [1, 1, 4, 5, 5, 5, 7] and sort it.
a=np.array([[1, 1, 4, 5, 5, 5, 7]])
b=np.unique(a)
b=np.sort(b)
b

array([1, 4, 5, 7])

In [194]:
a=np.array([1,2,3])
b=np.array([0,1,1])
c=np.dot(a,b)
print(c)

5


In [204]:
#Find the eigenvalues and eigenvectors of matrix A.
a=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
b,c=np.linalg.eig(a)
print(b)
print()
print(c)

[ 1.61168440e+01 -1.11684397e+00 -4.22209278e-16]

[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [207]:
#Given an array with [11, 22, 11, 31], [25, 33, 31, 28]]. Treat as floats. Find the correlation coefficients.
a=np.array([11, 22, 11, 31])
b=np.array([25, 33, 31, 28])
c=np.corrcoef(a,b)
print(c)

[[1.         0.15997968]
 [0.15997968 1.        ]]
